import { test, before, after, beforeEach } from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import { Pool } from "pg";
import { QiospayPayments } from "../src/server/qiospay-payments";
import { ensureQiospaySchema } from "../src/server/qiospay-schema";
import { crc16, validateStaticQr, validCallbackToken, normalizeCredits, parseMutationDate, fetchCredits, readQiospayConfig } from "../src/server/qiospay-client";
import { readQrisRecovery, storeQrisRecovery, qrisRecoveryKey, clearQrisRecoveryForIdentity } from "../src/lib/qrisRecovery";

// Fixtures only: never contact Qiospay or provision a live MikroTik voucher.
const qrBody = "0002010102115204000053033605802ID5908TESTSHOP6007JAKARTA6304";
const staticQr = qrBody + crc16(qrBody);
const fixtureConfig = () => ({
  qrisProvider: "qiospay", qrisEnabled: "true", qiospayMerchantCode: "TEST-MERCHANT",
  qiospayApiKey: "fixture-only-not-a-real-key", qiospayQrString: staticQr,
  qiospayCallbackToken: "a".repeat(64),
});
let config: Record<string, string>;
let ledger: any[] = [];
let fulfillCalls: string[] = [];
let failRouter = false;
let seq = 0;
let pool: Pool;
let root: Pool;
let payments: QiospayPayments;
const schemaName = `test_qiospay_${crypto.randomBytes(6).toString("hex")}`;
const pkg = { id: 1, router_id: 1, mikrotik_profile: "TEST" };
const fakeFetch: typeof fetch = async () => new Response(JSON.stringify({ status: "success", data: ledger }), { headers: { "Content-Type": "application/json" } });
const jakartaDate = (d: Date) => new Date(d.getTime() + 7 * 3600_000).toISOString().slice(0, 19).replace("T", " ");

before(async () => {
  assert.ok(process.env.DATABASE_URL, "DATABASE_URL required for isolated-schema integration tests");
  root = new Pool({ connectionString: process.env.DATABASE_URL });
  await root.query(`CREATE SCHEMA ${schemaName}`);
  pool = new Pool({ connectionString: process.env.DATABASE_URL, options: `-c search_path=${schemaName}`, max: 8 });
  await pool.query(`
    CREATE TABLE users(id INT PRIMARY KEY,name TEXT);
    CREATE TABLE routers(id INT PRIMARY KEY);
    CREATE TABLE packages(id INT PRIMARY KEY);
    CREATE TABLE settings(config_key TEXT PRIMARY KEY,config_value TEXT,updated_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE transactions(id SERIAL PRIMARY KEY,user_id INT,package_id INT,amount NUMERIC(10,2),
      payment_method TEXT,status VARCHAR(20),reference_id VARCHAR(100) UNIQUE,phone TEXT,voucher_code TEXT UNIQUE,created_at TIMESTAMPTZ DEFAULT NOW());
    INSERT INTO users VALUES(1,'Test User');
    INSERT INTO routers VALUES(1);
    INSERT INTO packages VALUES(1),(2);
  `);
  await ensureQiospaySchema(pool);
});
after(async () => {
  await pool?.end();
  // This name is generated by this test and contains only a fixed prefix+hex.
  if (root) { await root.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`); await root.end(); }
});
beforeEach(async () => {
  await pool.query("DELETE FROM qiospay_invoices; DELETE FROM qiospay_events; DELETE FROM transactions; DELETE FROM settings;");
  config = fixtureConfig(); ledger = []; fulfillCalls = []; failRouter = false;
  payments = new QiospayPayments(pool, async () => config, async () => `TEST-${++seq}`, async (_invoice, code) => {
    fulfillCalls.push(code);
    if (failRouter) throw new Error("fixture router unavailable");
  }, fakeFetch);
});
const order = (phone = "081234567891", packageData = pkg) => payments.create(packageData, 5000, 1, phone);
async function inWindow(reference: string) {
  await pool.query(
    "UPDATE qiospay_invoices SET created_at=NOW()-INTERVAL '2 minutes',expires_at=NOW()+INTERVAL '8 minutes' WHERE reference_id=$1", [reference],
  );
}
const credit = (amount: number, ref = "fixture-ref", date = new Date()) =>
  ({ amount: String(amount), type: "CR", date: jakartaDate(date), issuer_reff: ref, balance: "100000", brand_name: "TEST" });

test("startup schema is repeatable and preserves existing transactions and permanent reservations", async () => {
  const invoice = await order();
  const before = await pool.query("SELECT id,status,amount,reference_id FROM transactions ORDER BY id");
  await ensureQiospaySchema(pool);
  await ensureQiospaySchema(pool);
  assert.deepEqual((await pool.query("SELECT id,status,amount,reference_id FROM transactions ORDER BY id")).rows, before.rows);
  assert.equal((await pool.query("SELECT COUNT(*)::int AS count FROM qiospay_invoices")).rows[0].count, 1);
  assert.equal((await payments.status(invoice.reference_id))?.status, "pending");
});

test("QR validator accepts full static IDR QR and rejects corrupted/dynamic/amount-bearing QR", () => {
  assert.doesNotThrow(() => validateStaticQr(staticQr));
  assert.throws(() => validateStaticQr(staticQr.slice(0, -1) + "X"));
  const dynamic = qrBody.replace("010211", "010212");
  assert.throws(() => validateStaticQr(dynamic + crc16(dynamic)));
  const fixed = qrBody.replace("6304", "540450006304");
  assert.throws(() => validateStaticQr(fixed + crc16(fixed)));
  assert.throws(() => validateStaticQr("https://example.com/qr.png"));
});
test("callback secret check rejects missing/wrong/multibyte/unconfigured values", () => {
  assert.equal(validCallbackToken("a".repeat(64), "a".repeat(64)), true);
  assert.equal(validCallbackToken("b".repeat(64), "a".repeat(64)), false);
  assert.equal(validCallbackToken("é".repeat(64), "a".repeat(64)), false);
  assert.equal(validCallbackToken(undefined, ""), false);
  assert.equal(validCallbackToken("short", "short"), false);
});
test("mutasi dates explicitly use Jakarta time and reject invalid dates", () => {
  assert.equal(parseMutationDate("2026-10-02 22:00:00")?.toISOString(), "2026-10-02T15:00:00.000Z");
  assert.equal(parseMutationDate("2026-02-30 22:00:00"), null);
  assert.equal(parseMutationDate("02/10/2026 22:00"), null);
});
test("credit normalization ignores debits; deduplication is stable for equivalent values", () => {
  const row = { amount: "5100", type: "CR", date: "2026-10-02 22:00:00", balance: "15100", brand_name: "TEST" };
  assert.equal(normalizeCredits("TEST", [{ ...row, type: "DB" }]).length, 0);
  assert.equal(normalizeCredits("TEST", [row])[0].key, normalizeCredits("TEST", [{ ...row, amount: 5100, balance: "15100.00", qris: "static" }])[0].key);
  assert.throws(() => normalizeCredits("TEST", [{ ...row, date: "invalid" }]));
  assert.throws(() => normalizeCredits("TEST", [{ ...row, amount: "5.5" }]));
  assert.throws(() => normalizeCredits("TEST", [{ ...row, balance: undefined }]));
  assert.throws(() => normalizeCredits("TEST", [{ ...row, balance: "not-a-balance" }]));
});
test("provider failures do not disclose key-bearing URLs or provider messages", async () => {
  const c = readQiospayConfig(config);
  const broken: typeof fetch = async () => { throw new Error(`failed URL ${c.apiKey}`); };
  await assert.rejects(fetchCredits(c, broken), (e: Error) => !e.message.includes(c.apiKey) && e.message.includes("Tidak dapat"));
  const rejected: typeof fetch = async () => new Response(JSON.stringify({ status: "error", messages: c.apiKey }), { status: 403 });
  await assert.rejects(fetchCredits(c, rejected), (e: Error) => !e.message.includes(c.apiKey));
});
test("unconfigured/misconfigured/no-router checkout cannot take payment or mint voucher", async () => {
  config.qiospayApiKey = "";
  await assert.rejects(order(), /belum lengkap/);
  config = fixtureConfig();
  await assert.rejects(payments.create({ id: 1 }, 5000, 1, null), /router/);
  await assert.rejects(payments.create(pkg, 5000, null, "x"), /Nomor HP/);
  await assert.rejects(payments.create(pkg, 0, 1, null), /Harga/);
  assert.equal(fulfillCalls.length, 0);
});
test("creation renders QR locally, charges unique total, and reuses one active invoice", async () => {
  const a = await order();
  const b = await order();
  assert.equal(a.reference_id, b.reference_id);
  assert.equal(a.amount, 5000 + a.unique_code);
  assert.ok(a.unique_code >= 1 && a.unique_code <= 999);
  assert.match(a.qr_url, /^data:image\/png;base64,/);
  assert.equal(a.status, "pending");
  assert.equal(fulfillCalls.length, 0);
});
test("parallel buyers of the same package receive different totals", async () => {
  const results = await Promise.all([order("081234567891"), order("081234567892"), order("081234567893")]);
  assert.equal(new Set(results.map(r => r.amount)).size, 3);
  assert.equal(new Set(results.map(r => r.reference_id)).size, 3);
});
test("expired invoice total is never recycled, even for the same buyer", async () => {
  const a = await order();
  await pool.query("UPDATE qiospay_invoices SET expires_at=NOW()-INTERVAL '1 second' WHERE reference_id=$1", [a.reference_id]);
  assert.equal((await payments.status(a.reference_id))?.status, "expired");
  const b = await order();
  assert.notEqual(a.amount, b.amount);
});
test("already existing merchant credits cannot pay a new invoice", async () => {
  ledger = Array.from({ length: 998 }, (_, i) => credit(5001 + i, `old-${i}`, new Date(Date.now() - 86400_000)));
  const a = await order();
  assert.equal(a.amount, 5999);
  const data = await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "pending");
  assert.equal(data.reservations_count, 1);
  await assert.rejects(order("081234567899"), /habis/);
});
test("no ledger credit and wrong amounts never mint vouchers", async () => {
  const a = await order(); await inWindow(a.reference_id);
  await payments.sync();
  ledger = [credit(a.amount + 1), { ...credit(a.amount), type: "DB" }];
  await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "pending");
  assert.equal(fulfillCalls.length, 0);
});
test("verified ledger credit fulfills once across duplicate/concurrent syncs", async () => {
  const a = await order(); await inWindow(a.reference_id);
  ledger = [credit(a.amount)];
  await Promise.all([payments.sync(), payments.sync()]);
  await payments.sync();
  const status = await payments.status(a.reference_id);
  assert.equal(status?.status, "success");
  assert.equal(status?.voucher_code, fulfillCalls[0]);
  assert.equal(fulfillCalls.length, 1);
  assert.equal((await payments.overview()).events[0].status, "matched");
});
test("router outage keeps verified money and retries the SAME voucher candidate", async () => {
  const a = await order(); await inWindow(a.reference_id);
  ledger = [credit(a.amount)]; failRouter = true;
  await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "paid");
  assert.equal((await payments.status(a.reference_id))?.voucher_code, null);
  await payments.sync();
  assert.equal(fulfillCalls.length, 1, "backoff suppresses repeated provision");
  failRouter = false;
  await payments.provision(a.reference_id, true);
  assert.equal((await payments.status(a.reference_id))?.status, "success");
  assert.equal(fulfillCalls.length, 2);
  assert.equal(fulfillCalls[0], fulfillCalls[1]);
});
test("manual retry cannot mint a voucher before money is verified", async () => {
  const a = await order();
  await assert.rejects(payments.provision(a.reference_id, true), /Dana belum/);
  assert.equal(fulfillCalls.length, 0);
});
test("late payment is review-only and cannot mint a voucher", async () => {
  const a = await order();
  await pool.query("UPDATE qiospay_invoices SET created_at=NOW()-INTERVAL '20 minutes',expires_at=NOW()-INTERVAL '10 minutes' WHERE reference_id=$1", [a.reference_id]);
  ledger = [credit(a.amount)];
  await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "review");
  assert.equal((await payments.overview()).events[0].status, "review");
  assert.equal(fulfillCalls.length, 0);
});
test("delayed ledger delivery recovers an expired invoice paid INSIDE its window", async () => {
  const a = await order();
  await pool.query("UPDATE qiospay_invoices SET created_at=NOW()-INTERVAL '20 minutes',expires_at=NOW()-INTERVAL '10 minutes' WHERE reference_id=$1", [a.reference_id]);
  assert.equal((await payments.status(a.reference_id))?.status, "expired");
  ledger = [credit(a.amount, "delayed", new Date(Date.now() - 15 * 60_000))];
  await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "success");
  assert.equal(fulfillCalls.length, 1);
});
test("repeat actual payments do not create a second voucher; surplus is marked review", async () => {
  const a = await order(); await inWindow(a.reference_id);
  ledger = [credit(a.amount, "first"), credit(a.amount, "second")];
  await payments.sync();
  assert.equal(fulfillCalls.length, 1);
  const statuses = (await payments.overview()).events.map(e => e.status).sort();
  assert.deepEqual(statuses, ["matched", "review"]);
});
test("immutable ledger references reject changed amounts without minting", async () => {
  const a = await order(); await inWindow(a.reference_id);
  ledger = [credit(a.amount + 10, "immutable")];
  await payments.sync();
  ledger = [credit(a.amount, "immutable")];
  await assert.rejects(payments.sync(), /berubah/);
  assert.equal(fulfillCalls.length, 0);
});
test("nominal reservation blocks accidental removal of financial history", async () => {
  const a = await order();
  await assert.rejects(pool.query("DELETE FROM transactions WHERE reference_id=$1", [a.reference_id]), /foreign key/);
  assert.equal((await payments.status(a.reference_id))?.status, "pending");
});
test("browser receipt recovery is scoped, discards corrupt data, and never hydrates voucher fields", () => {
  const data = new Map<string, string>();
  (globalThis as any).window = { sessionStorage: {
    getItem: (k: string) => data.get(k) ?? null,
    setItem: (k: string, v: string) => data.set(k, v),
    removeItem: (k: string) => data.delete(k),
    key: (i: number) => [...data.keys()][i] ?? null,
    get length() { return data.size; },
  } };
  try {
    const a = qrisRecoveryKey("user-1", 1), b = qrisRecoveryKey("user-2", 1);
    const payment = { provider: "qiospay", reference_id: "TEST-REF", qr_url: "data:image/png;base64,AA==",
      amount: 5123, base_amount: 5000, unique_code: 123, expires_at: new Date(Date.now() + 60_000).toISOString() };
    storeQrisRecovery(a, { ...payment, voucher_code: "DO-NOT-HYDRATE" } as any);
    assert.equal(readQrisRecovery(a)?.reference_id, "TEST-REF");
    assert.equal((readQrisRecovery(a) as any).voucher_code, undefined);
    assert.equal(readQrisRecovery(b), null);
    storeQrisRecovery(b, payment);
    clearQrisRecoveryForIdentity("user-1");
    assert.equal(readQrisRecovery(a), null);
    assert.ok(readQrisRecovery(b));
    storeQrisRecovery(a, { ...payment, qr_url: "javascript:alert(1)" });
    assert.equal(readQrisRecovery(a), null);
    assert.equal(data.has(a), false);
    storeQrisRecovery(a, { ...payment, provider: "sanpay", unique_code: 0, amount: 5000,
      qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=test", expires_at: null } as any);
    assert.equal(readQrisRecovery(a), null, "Retired gateway receipts cannot reopen checkout");
    storeQrisRecovery(a, { ...payment, amount: 9999 });
    assert.equal(readQrisRecovery(a), null);
  } finally { delete (globalThis as any).window; }
});