import { test, before, after, beforeEach } from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import QRCode, { type QRCodeToDataURLOptions } from "qrcode";
import { readFile } from "node:fs/promises";
import { transformSync } from "esbuild";
import { Pool } from "pg";
import { QiospayPayments } from "../src/server/qiospay-payments";
import { ensureQiospaySchema } from "../src/server/qiospay-schema";
import { PaymentError, crc16, validateStaticQr, paymentQrString, validCallbackToken, normalizeCredits, parseMutationDate, fetchCredits, readQiospayConfig } from "../src/server/qiospay-client";
import { readQrisRecovery, storeQrisRecovery, qrisRecoveryKey, qrisTopupRecoveryKey, clearQrisRecoveryForIdentity, findLatestQrisRecovery } from "../src/lib/qrisRecovery";
import { readApiResponse, apiErrorMessage } from "../src/lib/apiResponse";

// Fixtures only: never contact Qiospay or provision a live MikroTik voucher.
const qrBody = "0002010102115204000053033605802ID5908TESTSHOP6007JAKARTA6304";
const staticQr = qrBody + crc16(qrBody);
const qrTags = (value: string) => {
  const tags = new Map<string, string>();
  for (let pos = 0; pos < value.length;) {
    const length = Number(value.slice(pos + 2, pos + 4));
    tags.set(value.slice(pos, pos + 2), value.slice(pos + 4, pos + 4 + length));
    pos += 4 + length;
  }
  return tags;
};
const fixtureConfig = () => ({
  qrisProvider: "qiospay", qrisEnabled: "true", qiospayMerchantCode: "TEST-MERCHANT",
  qiospayApiKey: "fixture-only-not-a-real-key", qiospayQrString: staticQr,
  qiospayCallbackToken: "a".repeat(64),
});
let config: Record<string, string>;
let ledger: any[] = [];
let fulfillCalls: string[] = [];
let failRouter = false;
let seq = 0;
let pool: Pool;
let root: Pool;
let payments: QiospayPayments;
const schemaName = `test_qiospay_${crypto.randomBytes(6).toString("hex")}`;
const pkg = { id: 1, router_id: 1, mikrotik_profile: "TEST" };
const fakeFetch: typeof fetch = async () => new Response(JSON.stringify({ status: "success", data: ledger }), { headers: { "Content-Type": "application/json" } });
const jakartaDate = (d: Date) => new Date(d.getTime() + 7 * 3600_000).toISOString().slice(0, 19).replace("T", " ");

before(async () => {
  assert.ok(process.env.DATABASE_URL, "DATABASE_URL required for isolated-schema integration tests");
  root = new Pool({ connectionString: process.env.DATABASE_URL });
  await root.query(`CREATE SCHEMA ${schemaName}`);
  pool = new Pool({ connectionString: process.env.DATABASE_URL, options: `-c search_path=${schemaName}`, max: 8 });
  await pool.query(`
    CREATE TABLE users(id INT PRIMARY KEY,name TEXT,balance NUMERIC(10,2) DEFAULT 0,status TEXT DEFAULT 'active',updated_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE topups(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id),admin_id INT REFERENCES users(id),
      amount NUMERIC(10,2) NOT NULL,type TEXT DEFAULT 'topup',idempotency_key TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
    CREATE UNIQUE INDEX topups_idempotency_key_idx ON topups(idempotency_key) WHERE idempotency_key IS NOT NULL;
    CREATE TABLE notifications(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id),title TEXT,body TEXT,type TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE routers(id INT PRIMARY KEY);
    CREATE TABLE packages(id INT PRIMARY KEY);
    CREATE TABLE settings(config_key TEXT PRIMARY KEY,config_value TEXT,updated_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE transactions(id SERIAL PRIMARY KEY,user_id INT,package_id INT,amount NUMERIC(10,2),
      payment_method TEXT,status VARCHAR(20),reference_id VARCHAR(100) UNIQUE,phone TEXT,voucher_code TEXT UNIQUE,created_at TIMESTAMPTZ DEFAULT NOW());
    INSERT INTO users(id,name) VALUES(1,'Test User'),(2,'Other Test User');
    INSERT INTO routers VALUES(1);
    INSERT INTO packages VALUES(1),(2);
  `);
  await ensureQiospaySchema(pool);
});
after(async () => {
  await pool?.end();
  // This name is generated by this test and contains only a fixed prefix+hex.
  if (root) { await root.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`); await root.end(); }
});
beforeEach(async () => {
  await pool.query("DELETE FROM qiospay_invoices; DELETE FROM qiospay_events; DELETE FROM transactions; DELETE FROM settings; DELETE FROM topups; DELETE FROM notifications; UPDATE users SET balance=0,status='active';");
  config = fixtureConfig(); ledger = []; fulfillCalls = []; failRouter = false;
  payments = new QiospayPayments(pool, async () => config, async () => `TEST-${++seq}`, async (_invoice, code) => {
    fulfillCalls.push(code);
    if (failRouter) throw new Error("fixture router unavailable");
  }, fakeFetch);
});
const order = (phone = "081234567891", packageData = pkg) => payments.create(packageData, 5000, 1, phone);
async function inWindow(reference: string) {
  await pool.query(
    "UPDATE qiospay_invoices SET created_at=NOW()-INTERVAL '2 minutes',expires_at=NOW()+INTERVAL '8 minutes' WHERE reference_id=$1", [reference],
  );
}
const credit = (amount: number, ref = "fixture-ref", date = new Date()) =>
  ({ amount: String(amount), type: "CR", date: jakartaDate(date), issuer_reff: ref, balance: "100000", brand_name: "TEST" });

test("QRIS settings save repairs missing tables, preserves other settings and keeps a saved key", async () => {
  // Exercise the actual monolithic server handler against this test's isolated
  // schema, without starting a second server or touching development settings.
  const source = await readFile(new URL("../server.ts", import.meta.url), "utf8");
  const start = source.indexOf('  app.post("/api/settings", requireAdmin,');
  const end = source.indexOf('  app.get("/api/config/public"', start);
  assert.ok(start >= 0 && end > start);
  let handler: any;
  const app = { post: (_path: string, _guard: unknown, callback: unknown) => { handler = callback; } };
  const code = transformSync(source.slice(start, end), { loader: "ts", target: "es2022" }).code;
  new Function("app", "requireAdmin", "pool", "ensureQiospaySchema", "crypto",
    "PaymentError", "validateStaticQr", "readQiospayConfig", "qiospayReady", code)(
      app, () => {}, pool, ensureQiospaySchema, crypto, PaymentError, validateStaticQr, readQiospayConfig,
      (s: Record<string, string>) => { try { readQiospayConfig(s); return true; } catch { return false; } },
    );
  const previous = {
    telegramToken: "fixture-telegram", telegramChatId: "fixture-chat",
    hotspotLoginUrl: "legacy-url", whatsappNumber: "123", whatsappMessage: "Keep this",
    voucherCharset: "numeric", voucherLength: "6", voucherPrefix: "legacy-prefix",
  };
  for (const [key, value] of Object.entries(previous)) {
    await pool.query("INSERT INTO settings(config_key,config_value) VALUES($1,$2)", [key, value]);
  }
  // These tables belong only to the generated test schema and are empty.
  await pool.query("DROP TABLE qiospay_invoices; DROP TABLE qiospay_events;");
  await pool.query("INSERT INTO transactions(amount,status,reference_id) VALUES(5000,'success','fixture-history')");
  const save = async (body: unknown) => {
    const result = { status: 200, json: null as any };
    const response = {
      status: (status: number) => { result.status = status; return response; },
      json: (json: unknown) => { result.json = json; return response; },
    };
    await handler({ body }, response);
    return result;
  };
  const body = {
    qiospayMerchantCode: "TEST-MERCHANT", qiospayQrString: staticQr,
    qiospayApiKey: "fixture-only-not-a-real-key", qrisEnabled: true,
  };
  assert.deepEqual(await save(body), { status: 200, json: { success: true, message: "Pengaturan berhasil disimpan." } });
  const read = async () => Object.fromEntries((await pool.query("SELECT config_key,config_value FROM settings")).rows.map(r => [r.config_key, r.config_value]));
  const saved = await read();
  for (const [key, value] of Object.entries(previous)) assert.equal(saved[key], value);
  assert.equal(saved.qrisEnabled, "true");
  assert.match(saved.qiospayCallbackToken, /^[a-f0-9]{64}$/);
  assert.equal((await pool.query("SELECT COUNT(*)::int AS count FROM qiospay_invoices")).rows[0].count, 0);
  assert.equal((await pool.query("SELECT status FROM transactions WHERE reference_id='fixture-history'")).rows[0].status, "success");
  assert.equal((await save({ ...body, qiospayApiKey: "" })).status, 200);
  assert.deepEqual(await read(), saved);
  assert.equal((await save({ ...body, qiospayQrString: "invalid" })).status, 400);
  assert.deepEqual(await read(), saved);
});

test("startup schema is repeatable and preserves existing transactions and permanent reservations", async () => {
  const invoice = await order();
  const before = await pool.query("SELECT id,status,amount,reference_id FROM transactions ORDER BY id");
  await ensureQiospaySchema(pool);
  await ensureQiospaySchema(pool);
  assert.deepEqual((await pool.query("SELECT id,status,amount,reference_id FROM transactions ORDER BY id")).rows, before.rows);
  assert.equal((await pool.query("SELECT COUNT(*)::int AS count FROM qiospay_invoices")).rows[0].count, 1);
  assert.equal((await payments.status(invoice.reference_id))?.status, "pending");
});

test("QR validator accepts full static IDR QR and rejects corrupted/dynamic/amount-bearing QR", () => {
  assert.doesNotThrow(() => validateStaticQr(staticQr));
  assert.throws(() => validateStaticQr(staticQr.slice(0, -1) + "X"));
  const dynamic = qrBody.replace("010211", "010212");
  assert.throws(() => validateStaticQr(dynamic + crc16(dynamic)));
  const fixed = qrBody.replace("6304", "540450006304");
  assert.throws(() => validateStaticQr(fixed + crc16(fixed)));
  assert.throws(() => validateStaticQr("https://example.com/qr.png"));
});
test("payment QR encodes the exact IDR amount, preserves merchant fields and recalculates CRC", () => {
  const body = qrBody.replace("5204", "26160004TEST0104SHOP5204").replace("6304", "62070503ABC6304");
  const merchantQr = body + crc16(body);
  const result = paymentQrString(merchantQr, 2001);
  const tags = qrTags(result);
  assert.equal(tags.get("01"), "12");
  assert.equal(tags.get("54"), "2001");
  assert.equal(result.slice(-4), crc16(result.slice(0, -4)));
  for (const [tag, value] of qrTags(merchantQr)) {
    if (tag !== "01" && tag !== "63") assert.equal(tags.get(tag), value);
  }
  assert.doesNotThrow(() => validateStaticQr(merchantQr));
  assert.throws(() => validateStaticQr(result));
  const noInitiation = qrBody.replace("010211", "");
  assert.equal(qrTags(paymentQrString(noInitiation + crc16(noInitiation), 5200)).get("01"), "12");
  for (const amount of [0, -1, 1.5, NaN, Infinity, 100_000_000]) {
    assert.throws(() => paymentQrString(merchantQr, amount), /Total pembayaran/);
  }
  assert.throws(() => paymentQrString(merchantQr.slice(0, -1) + "X", 2001));
});

test("API responses distinguish HTML, unavailable routes, proxy failures and real JSON errors", async () => {
  for (const [status, pattern] of [[200, /Respons API bukan JSON/], [404, /Endpoint API/], [502, /Server\/proxy/]] as const) {
    await assert.rejects(
      readApiResponse(new Response("<!DOCTYPE html><html>fixture</html>", { status, headers: { "Content-Type": "text/html" } })),
      pattern,
    );
  }
  await assert.rejects(readApiResponse(new Response("<html>invalid</html>", { headers: { "Content-Type": "application/json" } })), /bukan JSON/);
  await assert.rejects(readApiResponse(new Response('{"data":[]}', { headers: { "Content-Type": "application/json" } })), /Format respons/);
  const envelope = { success: false, error: "Fixture invalid key" };
  assert.deepEqual(await readApiResponse(new Response(JSON.stringify(envelope), { status: 400, headers: { "Content-Type": "application/json" } })), envelope);
  assert.equal(apiErrorMessage("Unexpected token '<', '<!DOCTYPE' is not valid JSON").includes("DOCTYPE"), false);
});

test("upstream HTML cannot verify a payment or provision any voucher", async () => {
  const invoice = await order();
  const htmlPayments = new QiospayPayments(pool, async () => config, async () => "UNUSED", async () => {
    assert.fail("An HTML response must never provision a voucher");
  }, async () => new Response("<!DOCTYPE html>fixture proxy page", { headers: { "Content-Type": "text/html" } }));
  await assert.rejects(htmlPayments.sync(), /Qiospay mengirim respons bukan JSON/);
  assert.equal((await payments.status(invoice.reference_id))?.status, "pending");
  assert.equal(fulfillCalls.length, 0);
  const { rows } = await pool.query("SELECT config_value FROM settings WHERE config_key='qiospaySyncError'");
  assert.match(rows[0].config_value, /HTTP 200/);
  assert.equal(rows[0].config_value.includes("DOCTYPE"), false);
});
test("callback secret check rejects missing/wrong/multibyte/unconfigured values", () => {
  assert.equal(validCallbackToken("a".repeat(64), "a".repeat(64)), true);
  assert.equal(validCallbackToken("b".repeat(64), "a".repeat(64)), false);
  assert.equal(validCallbackToken("é".repeat(64), "a".repeat(64)), false);
  assert.equal(validCallbackToken(undefined, ""), false);
  assert.equal(validCallbackToken("short", "short"), false);
});
test("mutasi dates explicitly use Jakarta time and reject invalid dates", () => {
  assert.equal(parseMutationDate("2026-10-02 22:00:00")?.toISOString(), "2026-10-02T15:00:00.000Z");
  assert.equal(parseMutationDate("2026-02-30 22:00:00"), null);
  assert.equal(parseMutationDate("02/10/2026 22:00"), null);
});
test("credit normalization ignores debits; deduplication is stable for equivalent values", () => {
  const row = { amount: "5100", type: "CR", date: "2026-10-02 22:00:00", balance: "15100", brand_name: "TEST" };
  assert.equal(normalizeCredits("TEST", [{ ...row, type: "DB" }]).length, 0);
  assert.equal(normalizeCredits("TEST", [row])[0].key, normalizeCredits("TEST", [{ ...row, amount: 5100, balance: "15100.00", qris: "static" }])[0].key);
  assert.throws(() => normalizeCredits("TEST", [{ ...row, date: "invalid" }]));
  assert.throws(() => normalizeCredits("TEST", [{ ...row, amount: "5.5" }]));
  assert.throws(() => normalizeCredits("TEST", [{ ...row, balance: undefined }]));
  assert.throws(() => normalizeCredits("TEST", [{ ...row, balance: "not-a-balance" }]));
});
test("provider failures do not disclose key-bearing URLs or provider messages", async () => {
  const c = readQiospayConfig(config);
  const broken: typeof fetch = async () => { throw new Error(`failed URL ${c.apiKey}`); };
  await assert.rejects(fetchCredits(c, broken), (e: Error) => !e.message.includes(c.apiKey) && e.message.includes("Tidak dapat"));
  const rejected: typeof fetch = async () => new Response(JSON.stringify({ status: "error", messages: c.apiKey }), { status: 403 });
  await assert.rejects(fetchCredits(c, rejected), (e: Error) => !e.message.includes(c.apiKey));
});
test("only the known HTTP 200 empty-ledger response normalizes to zero credits", async () => {
  const c = readQiospayConfig(config);
  for (const messages of ["Data not found.", "Data tidak ditemukan", "Mutasi tidak ditemukan"]) {
    const fetcher: typeof fetch = async () => new Response(JSON.stringify({ status: "error", messages }));
    assert.deepEqual(await fetchCredits(c, fetcher), []);
  }
  for (const body of [
    { status: "error", messages: "Merchant data not found" },
    { status: "error", messages: `API Key invalid: ${c.apiKey}. Data not found.` },
    { status: "error", messages: "Unknown failure" },
    { status: "error", messages: "Internal server error: Data not found" },
    { status: "error", messages: "Data not found", data: {} },
    { status: "error", messages: "Data not found", data: [credit(5100)] },
    { messages: "Data not found" },
  ]) {
    const fetcher: typeof fetch = async () => new Response(JSON.stringify(body));
    await assert.rejects(fetchCredits(c, fetcher), (e: Error) =>
      e.message.includes("Periksa Merchant Code") && !e.message.includes(c.apiKey));
  }
  const failedHttp: typeof fetch = async () => new Response(JSON.stringify({ status: "error", messages: "Data not found" }), { status: 403 });
  await assert.rejects(fetchCredits(c, failedHttp), /Periksa Merchant Code/);
  const emptySuccess: typeof fetch = async () => new Response(JSON.stringify({ status: "success", data: [] }));
  assert.deepEqual(await fetchCredits(c, emptySuccess), []);
});
test("an initially empty Qiospay ledger allows checkout but pays only a later matching credit", async () => {
  const fetcher: typeof fetch = async () => ledger.length
    ? fakeFetch("https://example.invalid/fixture")
    : new Response(JSON.stringify({ status: "error", messages: "Data not found." }));
  const emptyPayments = new QiospayPayments(pool, async () => config, async () => "TEST-EMPTY-LEDGER", async (_invoice, code) => {
    fulfillCalls.push(code);
  }, fetcher);
  const invoice = await emptyPayments.create(pkg, 5000, 1, "081234567891");
  assert.match(invoice.qr_url, /^data:image\/png;base64,/);
  assert.equal(invoice.status, "pending");
  assert.equal(invoice.amount, 5000 + invoice.unique_code);
  await inWindow(invoice.reference_id);
  await emptyPayments.sync();
  assert.equal((await payments.status(invoice.reference_id))?.status, "pending");
  assert.equal(fulfillCalls.length, 0);
  const { rows } = await pool.query("SELECT config_key,config_value FROM settings WHERE config_key IN ('qiospaySyncError','qiospayLastSyncAt')");
  assert.equal(rows.find(r => r.config_key === "qiospaySyncError")?.config_value, "");
  assert.ok(rows.some(r => r.config_key === "qiospayLastSyncAt" && r.config_value));
  const wrongCredit = credit(invoice.amount + 1, "wrong-amount");
  ledger = [wrongCredit];
  await emptyPayments.sync();
  assert.equal((await payments.status(invoice.reference_id))?.status, "pending");
  assert.equal(fulfillCalls.length, 0);
  ledger = [wrongCredit, credit(invoice.amount, "matching-amount")];
  await emptyPayments.sync();
  await emptyPayments.sync();
  assert.equal((await payments.status(invoice.reference_id))?.status, "success");
  assert.equal(fulfillCalls.length, 1);
});
test("HTTP 401 cannot create a QRIS invoice or provision a voucher even with an empty-data message", async () => {
  const rejectedPayments = new QiospayPayments(pool, async () => config, async () => "UNUSED", async () => {
    assert.fail("Rejected credentials must never provision a voucher");
  }, async () => new Response(JSON.stringify({ status: "error", messages: "Data not found" }), { status: 401 }));
  await assert.rejects(rejectedPayments.create(pkg, 5000, 1, "081234567891"), /Periksa Merchant Code/);
  const { rows } = await pool.query("SELECT COUNT(*)::int AS count FROM qiospay_invoices");
  assert.equal(rows[0].count, 0);
});
test("unconfigured/misconfigured/no-router checkout cannot take payment or mint voucher", async () => {
  config.qiospayApiKey = "";
  await assert.rejects(order(), /belum lengkap/);
  config = fixtureConfig();
  await assert.rejects(payments.create({ id: 1 }, 5000, 1, null), /router/);
  await assert.rejects(payments.create(pkg, 5000, null, "x"), /Nomor HP/);
  await assert.rejects(payments.create(pkg, 0, 1, null), /Harga/);
  assert.equal(fulfillCalls.length, 0);
});
test("creation renders QR locally, charges unique total, and reuses one active invoice", async () => {
  const encoded: string[] = [];
  const original = QRCode.toDataURL;
  QRCode.toDataURL = (async (text: string, options: QRCodeToDataURLOptions) => {
    encoded.push(text);
    return original(text, options);
  }) as unknown as typeof QRCode.toDataURL;
  try {
    const a = await order();
    const b = await order();
    assert.equal(a.reference_id, b.reference_id);
    assert.equal(a.amount, 5000 + a.unique_code);
    assert.equal(a.unique_code, 1);
    assert.match(a.qr_url, /^data:image\/png;base64,/);
    assert.equal(a.status, "pending");
    assert.equal(fulfillCalls.length, 0);
    assert.equal(encoded.length, 2);
    for (const qr of encoded) assert.equal(qrTags(qr).get("54"), String(a.amount));
    assert.equal(encoded[0], encoded[1]);
  } finally { QRCode.toDataURL = original; }
});
test("parallel buyers of the same package receive different totals", async () => {
  const results = await Promise.all([order("081234567891"), order("081234567892"), order("081234567893")]);
  assert.equal(new Set(results.map(r => r.amount)).size, 3);
  assert.deepEqual(results.map(r => r.unique_code).sort((a, b) => a - b), [1, 2, 3]);
  assert.equal(new Set(results.map(r => r.reference_id)).size, 3);
});
test("expired invoice total is never recycled, even for the same buyer", async () => {
  const a = await order();
  await pool.query("UPDATE qiospay_invoices SET expires_at=NOW()-INTERVAL '1 second' WHERE reference_id=$1", [a.reference_id]);
  assert.equal((await payments.status(a.reference_id))?.status, "expired");
  const b = await order();
  assert.notEqual(a.amount, b.amount);
  assert.equal(b.unique_code, 2);
});
test("a previous-day expired invoice keeps its nominal reserved", async () => {
  const a = await order();
  await pool.query("UPDATE qiospay_invoices SET created_at=NOW()-INTERVAL '2 days',expires_at=NOW()-INTERVAL '1 day' WHERE reference_id=$1", [a.reference_id]);
  const b = await order();
  assert.equal(b.unique_code, 2);
});
test("existing invoices with legacy codes above 200 retain their total and QR amount", async () => {
  const a = await order();
  await pool.query("UPDATE qiospay_invoices SET unique_code=900,total_amount=5900 WHERE reference_id=$1", [a.reference_id]);
  await pool.query("UPDATE transactions SET amount=5900 WHERE reference_id=$1", [a.reference_id]);
  const existing = await order();
  assert.equal(existing.reference_id, a.reference_id);
  assert.equal(existing.unique_code, 900);
  assert.equal(existing.amount, 5900);
  const next = await order("081234567892");
  assert.equal(next.unique_code, 1);
});
test("already existing merchant credits cannot pay a new invoice", async () => {
  ledger = Array.from({ length: 199 }, (_, i) => credit(5001 + i, `old-${i}`, new Date(Date.now() - 86400_000)));
  const a = await order();
  assert.equal(a.amount, 5200);
  const data = await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "pending");
  assert.equal(data.reservations_count, 1);
  await assert.rejects(order("081234567899"), /1–200.*habis/);
});
test("no ledger credit and wrong amounts never mint vouchers", async () => {
  const a = await order(); await inWindow(a.reference_id);
  await payments.sync();
  ledger = [credit(a.amount + 1), { ...credit(a.amount), type: "DB" }];
  await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "pending");
  assert.equal(fulfillCalls.length, 0);
});
test("verified ledger credit fulfills once across duplicate/concurrent syncs", async () => {
  const a = await order(); await inWindow(a.reference_id);
  ledger = [credit(a.amount)];
  await Promise.all([payments.sync(), payments.sync()]);
  await payments.sync();
  const status = await payments.status(a.reference_id);
  assert.equal(status?.status, "success");
  assert.equal(status?.voucher_code, fulfillCalls[0]);
  assert.equal(fulfillCalls.length, 1);
  assert.equal((await payments.overview()).events[0].status, "matched");
});
test("router outage keeps verified money and retries the SAME voucher candidate", async () => {
  const a = await order(); await inWindow(a.reference_id);
  ledger = [credit(a.amount)]; failRouter = true;
  await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "paid");
  assert.equal((await payments.status(a.reference_id))?.voucher_code, null);
  await payments.sync();
  assert.equal(fulfillCalls.length, 1, "backoff suppresses repeated provision");
  failRouter = false;
  await payments.provision(a.reference_id, true);
  assert.equal((await payments.status(a.reference_id))?.status, "success");
  assert.equal(fulfillCalls.length, 2);
  assert.equal(fulfillCalls[0], fulfillCalls[1]);
});
test("manual retry cannot mint a voucher before money is verified", async () => {
  const a = await order();
  await assert.rejects(payments.provision(a.reference_id, true), /Dana belum/);
  assert.equal(fulfillCalls.length, 0);
});
test("late payment is review-only and cannot mint a voucher", async () => {
  const a = await order();
  await pool.query("UPDATE qiospay_invoices SET created_at=NOW()-INTERVAL '20 minutes',expires_at=NOW()-INTERVAL '10 minutes' WHERE reference_id=$1", [a.reference_id]);
  ledger = [credit(a.amount)];
  await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "review");
  assert.equal((await payments.overview()).events[0].status, "review");
  assert.equal(fulfillCalls.length, 0);
});
test("delayed ledger delivery recovers an expired invoice paid INSIDE its window", async () => {
  const a = await order();
  await pool.query("UPDATE qiospay_invoices SET created_at=NOW()-INTERVAL '20 minutes',expires_at=NOW()-INTERVAL '10 minutes' WHERE reference_id=$1", [a.reference_id]);
  assert.equal((await payments.status(a.reference_id))?.status, "expired");
  ledger = [credit(a.amount, "delayed", new Date(Date.now() - 15 * 60_000))];
  await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "success");
  assert.equal(fulfillCalls.length, 1);
});
test("repeat actual payments do not create a second voucher; surplus is marked review", async () => {
  const a = await order(); await inWindow(a.reference_id);
  ledger = [credit(a.amount, "first"), credit(a.amount, "second")];
  await payments.sync();
  assert.equal(fulfillCalls.length, 1);
  const statuses = (await payments.overview()).events.map(e => e.status).sort();
  assert.deepEqual(statuses, ["matched", "review"]);
});
test("immutable ledger references reject changed amounts without minting", async () => {
  const a = await order(); await inWindow(a.reference_id);
  ledger = [credit(a.amount + 10, "immutable")];
  await payments.sync();
  ledger = [credit(a.amount, "immutable")];
  await assert.rejects(payments.sync(), /berubah/);
  assert.equal(fulfillCalls.length, 0);
});
test("wallet top-up credits base amount once, records one receipt/notification, and never provisions MikroTik", async () => {
  const a = await payments.createTopup(10000, 1);
  await inWindow(a.reference_id);
  ledger = [credit(a.amount, "topup-one")];
  await Promise.all([payments.sync(), payments.sync()]);
  await payments.sync();
  await Promise.all([payments.provision(a.reference_id), payments.provision(a.reference_id)]);
  const status = await payments.status(a.reference_id, 1);
  assert.equal(status?.status, "success");
  assert.equal(status?.credited_amount, 10000);
  assert.equal(status?.voucher_code, null);
  assert.equal(Number((await pool.query("SELECT balance FROM users WHERE id=1")).rows[0].balance), 10000);
  assert.equal((await pool.query("SELECT * FROM topups")).rows.length, 1);
  assert.equal((await pool.query("SELECT * FROM notifications")).rows.length, 1);
  assert.equal(fulfillCalls.length, 0);
});
test("top-up invoices reuse only same customer's same pending amount and share voucher nominal reservations", async () => {
  const voucher = await order();
  const a = await payments.createTopup(5000, 1);
  const same = await payments.createTopup(5000, 1);
  const other = await payments.createTopup(5000, 2);
  assert.equal(same.reference_id, a.reference_id);
  assert.deepEqual([voucher.unique_code, a.unique_code, other.unique_code], [1, 2, 3]);
  assert.notEqual(other.reference_id, a.reference_id);
  assert.equal(a.purpose, "topup");
  assert.equal((await pool.query("SELECT router_id FROM qiospay_invoices WHERE reference_id=$1", [a.reference_id])).rows[0].router_id, null);
});
test("top-up status requires the owning session and cannot leak through public voucher status", async () => {
  const a = await payments.createTopup(10000, 1);
  assert.equal((await payments.status(a.reference_id, 1))?.status, "pending");
  await assert.rejects(payments.status(a.reference_id), (e: PaymentError) => e.status === 404);
  await assert.rejects(payments.status(a.reference_id, 2), (e: PaymentError) => e.status === 404);
});
test("top-up rejects invalid identity/amount, inactive accounts and disabled QRIS", async () => {
  for (const amount of [0, -1, 1.5, NaN, 99998999 + 1]) await assert.rejects(payments.createTopup(amount, 1));
  await assert.rejects(payments.createTopup(10000, null as any), (e: PaymentError) => e.status === 401);
  await assert.rejects(payments.createTopup(10000, 999), (e: PaymentError) => e.status === 403);
  await pool.query("UPDATE users SET status='inactive' WHERE id=1");
  await assert.rejects(payments.createTopup(10000, 1), (e: PaymentError) => e.status === 403);
  await pool.query("UPDATE users SET status='active' WHERE id=1");
  config.qrisEnabled = "false";
  await assert.rejects(payments.createTopup(10000, 1), (e: PaymentError) => e.status === 409);
  assert.equal((await pool.query("SELECT COUNT(*)::int AS n FROM qiospay_invoices")).rows[0].n, 0);
});
test("wrong amount, callback-only proof, and late ledger payments cannot credit the wallet", async () => {
  const a = await payments.createTopup(10000, 1);
  await inWindow(a.reference_id);
  await payments.provision(a.reference_id);
  ledger = [credit(a.base_amount, "wrong-topup")];
  await payments.sync();
  assert.equal((await payments.status(a.reference_id, 1))?.status, "pending");
  await pool.query("UPDATE qiospay_invoices SET created_at=NOW()-INTERVAL '20 minutes',expires_at=NOW()-INTERVAL '10 minutes' WHERE reference_id=$1", [a.reference_id]);
  ledger = [credit(a.amount, "late-topup")];
  await payments.sync();
  assert.equal((await payments.status(a.reference_id, 1))?.status, "review");
  assert.equal(Number((await pool.query("SELECT balance FROM users WHERE id=1")).rows[0].balance), 0);
  assert.equal((await pool.query("SELECT * FROM topups")).rows.length, 0);
});
test("wallet balance, history, status and notification roll back together; verified money recovers without provider", async () => {
  const a = await payments.createTopup(10000, 1);
  await inWindow(a.reference_id);
  await pool.query("ALTER TABLE notifications ADD CONSTRAINT fixture_reject_topup CHECK(title <> 'Top Up QRIS Berhasil')");
  try {
    ledger = [credit(a.amount, "rollback-topup")];
    await payments.sync();
    assert.equal((await payments.status(a.reference_id, 1))?.status, "paid");
    assert.equal(Number((await pool.query("SELECT balance FROM users WHERE id=1")).rows[0].balance), 0);
    assert.equal((await pool.query("SELECT * FROM topups")).rows.length, 0);
    assert.equal((await pool.query("SELECT * FROM notifications")).rows.length, 0);
  } finally { await pool.query("ALTER TABLE notifications DROP CONSTRAINT fixture_reject_topup"); }
  const offline = new QiospayPayments(pool, async () => config, async () => { throw new Error("no voucher"); },
    async () => { throw new Error("no router"); }, async () => { throw new Error("provider unavailable"); });
  await offline.provision(a.reference_id, true);
  await offline.provision(a.reference_id, true);
  assert.equal((await offline.status(a.reference_id, 1))?.status, "success");
  assert.equal(Number((await pool.query("SELECT balance FROM users WHERE id=1")).rows[0].balance), 10000);
  assert.equal((await pool.query("SELECT * FROM topups")).rows.length, 1);
  assert.equal((await pool.query("SELECT * FROM notifications")).rows.length, 1);
});
test("two different top-ups on one wallet accumulate atomically; duplicate actual payments go to review", async () => {
  const a = await payments.createTopup(10000, 1);
  const b = await payments.createTopup(20000, 1);
  await inWindow(a.reference_id); await inWindow(b.reference_id);
  ledger = [credit(a.amount, "wallet-a"), credit(b.amount, "wallet-b"), credit(a.amount, "wallet-extra")];
  await payments.sync();
  await payments.sync();
  assert.equal(Number((await pool.query("SELECT balance FROM users WHERE id=1")).rows[0].balance), 30000);
  assert.equal((await pool.query("SELECT * FROM topups")).rows.length, 2);
  assert.equal((await payments.overview()).events.filter(e => e.status === "review").length, 1);
});
test("top-up HTTP routes require auth, ignore body identity, validate input and scope history/status to the session", async () => {
  const source = await readFile(new URL("../server.ts", import.meta.url), "utf8");
  const start = source.indexOf('  app.post("/api/payment/topup-qris",');
  const end = source.indexOf('  app.post("/api/payment/create-qris",', start);
  assert.ok(start >= 0 && end > start);
  const routes = new Map<string, any[]>();
  const auth = () => {};
  const limiter = () => {};
  const app = {
    post: (path: string, ...handlers: any[]) => routes.set(`POST ${path}`, handlers),
    get: (path: string, ...handlers: any[]) => routes.set(`GET ${path}`, handlers),
  };
  new Function("app", "requireAuth", "qrisLimiter", "getSettings", "qiospay", "pool", "PaymentError",
    transformSync(source.slice(start, end), { loader: "ts", format: "cjs" }).code)(
    app, auth, limiter, async () => config, {
      createTopup: payments.createTopup.bind(payments),
      status: payments.status.bind(payments), requestSync: () => {},
    }, pool, PaymentError);
  for (const handlers of routes.values()) assert.equal(handlers[0], auth);
  const invoke = async (route: string, userId: number, body: any = {}, params: any = {}) => {
    const result = { status: 200, json: null as any };
    const res = {
      status: (n: number) => { result.status = n; return res; },
      json: (json: unknown) => { result.json = json; return res; },
    };
    const handlers = routes.get(route)!;
    await handlers.at(-1)({ body, params, session: { userId } }, res);
    return result;
  };
  for (const amount of [0, -5, 1.5, "10000", 100000000]) {
    assert.equal((await invoke("POST /api/payment/topup-qris", 1, { amount })).status, 400);
  }
  const a = (await invoke("POST /api/payment/topup-qris", 1, { amount: 10000, user_id: 2 })).json.data;
  assert.equal((await pool.query("SELECT user_id FROM transactions WHERE reference_id=$1", [a.reference_id])).rows[0].user_id, 1);
  assert.equal((await invoke("GET /api/payment/topup-status/:refId", 2, {}, { refId: a.reference_id })).status, 404);
  await inWindow(a.reference_id);
  ledger = [credit(a.amount, "http-wallet-one")];
  await payments.sync();
  const b = await payments.createTopup(20000, 2);
  await inWindow(b.reference_id);
  ledger.push(credit(b.amount, "http-wallet-two"));
  await payments.sync();
  const own = await invoke("GET /api/payment/topup-history", 1, { user_id: 2 });
  assert.equal(own.json.data.length, 1);
  assert.equal(own.json.data[0].amount, 10000);
  assert.equal(own.json.data[0].reference_id, a.reference_id);
  assert.equal(own.json.data[0].payment_method, "QRIS Qiospay");
  const status = await invoke("GET /api/payment/topup-status/:refId", 1, {}, { refId: a.reference_id });
  assert.equal(status.json.data.credited_amount, 10000);
});
test("nominal reservation blocks accidental removal of financial history", async () => {
  const a = await order();
  await assert.rejects(pool.query("DELETE FROM transactions WHERE reference_id=$1", [a.reference_id]), /foreign key/);
  assert.equal((await payments.status(a.reference_id))?.status, "pending");
});
test("browser receipt recovery is scoped, discards corrupt data, and never hydrates voucher fields", () => {
  const data = new Map<string, string>();
  (globalThis as any).window = { sessionStorage: {
    getItem: (k: string) => data.get(k) ?? null,
    setItem: (k: string, v: string) => data.set(k, v),
    removeItem: (k: string) => data.delete(k),
    key: (i: number) => [...data.keys()][i] ?? null,
    get length() { return data.size; },
  } };
  try {
    const a = qrisRecoveryKey("user-1", 1), b = qrisRecoveryKey("user-2", 1);
    const payment = { provider: "qiospay", reference_id: "TEST-REF", qr_url: "data:image/png;base64,AA==",
      amount: 5123, base_amount: 5000, unique_code: 123, expires_at: new Date(Date.now() + 60_000).toISOString() };
    storeQrisRecovery(a, { ...payment, voucher_code: "DO-NOT-HYDRATE" } as any);
    assert.equal(readQrisRecovery(a)?.reference_id, "TEST-REF");
    assert.equal((readQrisRecovery(a) as any).voucher_code, undefined);
    assert.equal(readQrisRecovery(b), null);
    storeQrisRecovery(b, payment);
    const topupKey = qrisTopupRecoveryKey("1");
    storeQrisRecovery(topupKey, { ...payment, purpose: "topup" });
    assert.equal(readQrisRecovery(topupKey)?.purpose, "topup");
    assert.equal(findLatestQrisRecovery("user-1")?.packageId, "1");
    clearQrisRecoveryForIdentity("user-1");
    assert.equal(readQrisRecovery(a), null);
    assert.equal(readQrisRecovery(topupKey), null);
    assert.ok(readQrisRecovery(b));
    storeQrisRecovery(a, { ...payment, qr_url: "javascript:alert(1)" });
    assert.equal(readQrisRecovery(a), null);
    assert.equal(data.has(a), false);
    storeQrisRecovery(a, { ...payment, provider: "sanpay", unique_code: 0, amount: 5000,
      qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=test", expires_at: null } as any);
    assert.equal(readQrisRecovery(a), null, "Retired gateway receipts cannot reopen checkout");
    storeQrisRecovery(a, { ...payment, amount: 9999 });
    assert.equal(readQrisRecovery(a), null);
  } finally { delete (globalThis as any).window; }
});