import { test, before, after, beforeEach } from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import { readFile } from "node:fs/promises";
import { transformSync } from "esbuild";
import { Pool } from "pg";
import { QiospayPayments } from "../src/server/qiospay-payments";
import { ensureQiospaySchema } from "../src/server/qiospay-schema";
import { PaymentError, crc16, validateStaticQr, validCallbackToken, normalizeCredits, parseMutationDate, fetchCredits, readQiospayConfig } from "../src/server/qiospay-client";
import { readQrisRecovery, storeQrisRecovery, qrisRecoveryKey, clearQrisRecoveryForIdentity } from "../src/lib/qrisRecovery";
import { readApiResponse, apiErrorMessage } from "../src/lib/apiResponse";

// Fixtures only: never contact Qiospay or provision a live MikroTik voucher.
const qrBody = "0002010102115204000053033605802ID5908TESTSHOP6007JAKARTA6304";
const staticQr = qrBody + crc16(qrBody);
const fixtureConfig = () => ({
  qrisProvider: "qiospay", qrisEnabled: "true", qiospayMerchantCode: "TEST-MERCHANT",
  qiospayApiKey: "fixture-only-not-a-real-key", qiospayQrString: staticQr,
  qiospayCallbackToken: "a".repeat(64),
});
let config: Record<string, string>;
let ledger: any[] = [];
let fulfillCalls: string[] = [];
let failRouter = false;
let seq = 0;
let pool: Pool;
let root: Pool;
let payments: QiospayPayments;
const schemaName = `test_qiospay_${crypto.randomBytes(6).toString("hex")}`;
const pkg = { id: 1, router_id: 1, mikrotik_profile: "TEST" };
const fakeFetch: typeof fetch = async () => new Response(JSON.stringify({ status: "success", data: ledger }), { headers: { "Content-Type": "application/json" } });
const jakartaDate = (d: Date) => new Date(d.getTime() + 7 * 3600_000).toISOString().slice(0, 19).replace("T", " ");

before(async () => {
  assert.ok(process.env.DATABASE_URL, "DATABASE_URL required for isolated-schema integration tests");
  root = new Pool({ connectionString: process.env.DATABASE_URL });
  await root.query(`CREATE SCHEMA ${schemaName}`);
  pool = new Pool({ connectionString: process.env.DATABASE_URL, options: `-c search_path=${schemaName}`, max: 8 });
  await pool.query(`
    CREATE TABLE users(id INT PRIMARY KEY,name TEXT);
    CREATE TABLE routers(id INT PRIMARY KEY);
    CREATE TABLE packages(id INT PRIMARY KEY);
    CREATE TABLE settings(config_key TEXT PRIMARY KEY,config_value TEXT,updated_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE transactions(id SERIAL PRIMARY KEY,user_id INT,package_id INT,amount NUMERIC(10,2),
      payment_method TEXT,status VARCHAR(20),reference_id VARCHAR(100) UNIQUE,phone TEXT,voucher_code TEXT UNIQUE,created_at TIMESTAMPTZ DEFAULT NOW());
    INSERT INTO users VALUES(1,'Test User');
    INSERT INTO routers VALUES(1);
    INSERT INTO packages VALUES(1),(2);
  `);
  await ensureQiospaySchema(pool);
});
after(async () => {
  await pool?.end();
  // This name is generated by this test and contains only a fixed prefix+hex.
  if (root) { await root.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`); await root.end(); }
});
beforeEach(async () => {
  await pool.query("DELETE FROM qiospay_invoices; DELETE FROM qiospay_events; DELETE FROM transactions; DELETE FROM settings;");
  config = fixtureConfig(); ledger = []; fulfillCalls = []; failRouter = false;
  payments = new QiospayPayments(pool, async () => config, async () => `TEST-${++seq}`, async (_invoice, code) => {
    fulfillCalls.push(code);
    if (failRouter) throw new Error("fixture router unavailable");
  }, fakeFetch);
});
const order = (phone = "081234567891", packageData = pkg) => payments.create(packageData, 5000, 1, phone);
async function inWindow(reference: string) {
  await pool.query(
    "UPDATE qiospay_invoices SET created_at=NOW()-INTERVAL '2 minutes',expires_at=NOW()+INTERVAL '8 minutes' WHERE reference_id=$1", [reference],
  );
}
const credit = (amount: number, ref = "fixture-ref", date = new Date()) =>
  ({ amount: String(amount), type: "CR", date: jakartaDate(date), issuer_reff: ref, balance: "100000", brand_name: "TEST" });

test("QRIS settings save repairs missing tables, preserves other settings and keeps a saved key", async () => {
  // Exercise the actual monolithic server handler against this test's isolated
  // schema, without starting a second server or touching development settings.
  const source = await readFile(new URL("../server.ts", import.meta.url), "utf8");
  const start = source.indexOf('  app.post("/api/settings", requireAdmin,');
  const end = source.indexOf('  app.get("/api/config/public"', start);
  assert.ok(start >= 0 && end > start);
  let handler: any;
  const app = { post: (_path: string, _guard: unknown, callback: unknown) => { handler = callback; } };
  const code = transformSync(source.slice(start, end), { loader: "ts", target: "es2022" }).code;
  new Function("app", "requireAdmin", "pool", "ensureQiospaySchema", "crypto",
    "PaymentError", "validateStaticQr", "readQiospayConfig", "qiospayReady", code)(
      app, () => {}, pool, ensureQiospaySchema, crypto, PaymentError, validateStaticQr, readQiospayConfig,
      (s: Record<string, string>) => { try { readQiospayConfig(s); return true; } catch { return false; } },
    );
  const previous = {
    telegramToken: "fixture-telegram", telegramChatId: "fixture-chat",
    hotspotLoginUrl: "legacy-url", whatsappNumber: "123", whatsappMessage: "Keep this",
    voucherCharset: "numeric", voucherLength: "6", voucherPrefix: "legacy-prefix",
  };
  for (const [key, value] of Object.entries(previous)) {
    await pool.query("INSERT INTO settings(config_key,config_value) VALUES($1,$2)", [key, value]);
  }
  // These tables belong only to the generated test schema and are empty.
  await pool.query("DROP TABLE qiospay_invoices; DROP TABLE qiospay_events;");
  await pool.query("INSERT INTO transactions(amount,status,reference_id) VALUES(5000,'success','fixture-history')");
  const save = async (body: unknown) => {
    const result = { status: 200, json: null as any };
    const response = {
      status: (status: number) => { result.status = status; return response; },
      json: (json: unknown) => { result.json = json; return response; },
    };
    await handler({ body }, response);
    return result;
  };
  const body = {
    qiospayMerchantCode: "TEST-MERCHANT", qiospayQrString: staticQr,
    qiospayApiKey: "fixture-only-not-a-real-key", qrisEnabled: true,
  };
  assert.deepEqual(await save(body), { status: 200, json: { success: true, message: "Pengaturan berhasil disimpan." } });
  const read = async () => Object.fromEntries((await pool.query("SELECT config_key,config_value FROM settings")).rows.map(r => [r.config_key, r.config_value]));
  const saved = await read();
  for (const [key, value] of Object.entries(previous)) assert.equal(saved[key], value);
  assert.equal(saved.qrisEnabled, "true");
  assert.match(saved.qiospayCallbackToken, /^[a-f0-9]{64}$/);
  assert.equal((await pool.query("SELECT COUNT(*)::int AS count FROM qiospay_invoices")).rows[0].count, 0);
  assert.equal((await pool.query("SELECT status FROM transactions WHERE reference_id='fixture-history'")).rows[0].status, "success");
  assert.equal((await save({ ...body, qiospayApiKey: "" })).status, 200);
  assert.deepEqual(await read(), saved);
  assert.equal((await save({ ...body, qiospayQrString: "invalid" })).status, 400);
  assert.deepEqual(await read(), saved);
});

test("startup schema is repeatable and preserves existing transactions and permanent reservations", async () => {
  const invoice = await order();
  const before = await pool.query("SELECT id,status,amount,reference_id FROM transactions ORDER BY id");
  await ensureQiospaySchema(pool);
  await ensureQiospaySchema(pool);
  assert.deepEqual((await pool.query("SELECT id,status,amount,reference_id FROM transactions ORDER BY id")).rows, before.rows);
  assert.equal((await pool.query("SELECT COUNT(*)::int AS count FROM qiospay_invoices")).rows[0].count, 1);
  assert.equal((await payments.status(invoice.reference_id))?.status, "pending");
});

test("QR validator accepts full static IDR QR and rejects corrupted/dynamic/amount-bearing QR", () => {
  assert.doesNotThrow(() => validateStaticQr(staticQr));
  assert.throws(() => validateStaticQr(staticQr.slice(0, -1) + "X"));
  const dynamic = qrBody.replace("010211", "010212");
  assert.throws(() => validateStaticQr(dynamic + crc16(dynamic)));
  const fixed = qrBody.replace("6304", "540450006304");
  assert.throws(() => validateStaticQr(fixed + crc16(fixed)));
  assert.throws(() => validateStaticQr("https://example.com/qr.png"));
});

test("API responses distinguish HTML, unavailable routes, proxy failures and real JSON errors", async () => {
  for (const [status, pattern] of [[200, /Respons API bukan JSON/], [404, /Endpoint API/], [502, /Server\/proxy/]] as const) {
    await assert.rejects(
      readApiResponse(new Response("<!DOCTYPE html><html>fixture</html>", { status, headers: { "Content-Type": "text/html" } })),
      pattern,
    );
  }
  await assert.rejects(readApiResponse(new Response("<html>invalid</html>", { headers: { "Content-Type": "application/json" } })), /bukan JSON/);
  await assert.rejects(readApiResponse(new Response('{"data":[]}', { headers: { "Content-Type": "application/json" } })), /Format respons/);
  const envelope = { success: false, error: "Fixture invalid key" };
  assert.deepEqual(await readApiResponse(new Response(JSON.stringify(envelope), { status: 400, headers: { "Content-Type": "application/json" } })), envelope);
  assert.equal(apiErrorMessage("Unexpected token '<', '<!DOCTYPE' is not valid JSON").includes("DOCTYPE"), false);
});

test("upstream HTML cannot verify a payment or provision any voucher", async () => {
  const invoice = await order();
  const htmlPayments = new QiospayPayments(pool, async () => config, async () => "UNUSED", async () => {
    assert.fail("An HTML response must never provision a voucher");
  }, async () => new Response("<!DOCTYPE html>fixture proxy page", { headers: { "Content-Type": "text/html" } }));
  await assert.rejects(htmlPayments.sync(), /Qiospay mengirim respons bukan JSON/);
  assert.equal((await payments.status(invoice.reference_id))?.status, "pending");
  assert.equal(fulfillCalls.length, 0);
  const { rows } = await pool.query("SELECT config_value FROM settings WHERE config_key='qiospaySyncError'");
  assert.match(rows[0].config_value, /HTTP 200/);
  assert.equal(rows[0].config_value.includes("DOCTYPE"), false);
});
test("callback secret check rejects missing/wrong/multibyte/unconfigured values", () => {
  assert.equal(validCallbackToken("a".repeat(64), "a".repeat(64)), true);
  assert.equal(validCallbackToken("b".repeat(64), "a".repeat(64)), false);
  assert.equal(validCallbackToken("é".repeat(64), "a".repeat(64)), false);
  assert.equal(validCallbackToken(undefined, ""), false);
  assert.equal(validCallbackToken("short", "short"), false);
});
test("mutasi dates explicitly use Jakarta time and reject invalid dates", () => {
  assert.equal(parseMutationDate("2026-10-02 22:00:00")?.toISOString(), "2026-10-02T15:00:00.000Z");
  assert.equal(parseMutationDate("2026-02-30 22:00:00"), null);
  assert.equal(parseMutationDate("02/10/2026 22:00"), null);
});
test("credit normalization ignores debits; deduplication is stable for equivalent values", () => {
  const row = { amount: "5100", type: "CR", date: "2026-10-02 22:00:00", balance: "15100", brand_name: "TEST" };
  assert.equal(normalizeCredits("TEST", [{ ...row, type: "DB" }]).length, 0);
  assert.equal(normalizeCredits("TEST", [row])[0].key, normalizeCredits("TEST", [{ ...row, amount: 5100, balance: "15100.00", qris: "static" }])[0].key);
  assert.throws(() => normalizeCredits("TEST", [{ ...row, date: "invalid" }]));
  assert.throws(() => normalizeCredits("TEST", [{ ...row, amount: "5.5" }]));
  assert.throws(() => normalizeCredits("TEST", [{ ...row, balance: undefined }]));
  assert.throws(() => normalizeCredits("TEST", [{ ...row, balance: "not-a-balance" }]));
});
test("provider failures do not disclose key-bearing URLs or provider messages", async () => {
  const c = readQiospayConfig(config);
  const broken: typeof fetch = async () => { throw new Error(`failed URL ${c.apiKey}`); };
  await assert.rejects(fetchCredits(c, broken), (e: Error) => !e.message.includes(c.apiKey) && e.message.includes("Tidak dapat"));
  const rejected: typeof fetch = async () => new Response(JSON.stringify({ status: "error", messages: c.apiKey }), { status: 403 });
  await assert.rejects(fetchCredits(c, rejected), (e: Error) => !e.message.includes(c.apiKey));
});
test("missing mutation data has a safe distinct error, never a successful ledger", async () => {
  const c = readQiospayConfig(config);
  for (const messages of ["Data not found.", "Data tidak ditemukan", "Mutasi tidak ditemukan"]) {
    const fetcher: typeof fetch = async () => new Response(JSON.stringify({ status: "error", messages }));
    await assert.rejects(fetchCredits(c, fetcher), (e: PaymentError) =>
      e.status === 502 && e.message.includes("Mutasi Qiospay belum tersedia") && !e.message.includes("API Key"));
  }
  for (const body of [
    { status: "error", messages: "Merchant data not found" },
    { status: "error", messages: `API Key invalid: ${c.apiKey}. Data not found.` },
    { status: "error", messages: "Unknown failure" },
    { status: "error", messages: "Data not found", data: [credit(5100)] },
    { messages: "Data not found" },
  ]) {
    const fetcher: typeof fetch = async () => new Response(JSON.stringify(body));
    await assert.rejects(fetchCredits(c, fetcher), (e: Error) =>
      e.message.includes("Periksa Merchant Code") && !e.message.includes(c.apiKey));
  }
  const failedHttp: typeof fetch = async () => new Response(JSON.stringify({ status: "error", messages: "Data not found" }), { status: 403 });
  await assert.rejects(fetchCredits(c, failedHttp), /Periksa Merchant Code/);
  const emptySuccess: typeof fetch = async () => new Response(JSON.stringify({ status: "success", data: [] }));
  assert.deepEqual(await fetchCredits(c, emptySuccess), []);
});
test("missing mutation data cannot provision vouchers or advance last successful sync", async () => {
  const invoice = await order();
  await inWindow(invoice.reference_id);
  const emptyPayments = new QiospayPayments(pool, async () => config, async () => "UNUSED", async () => {
    assert.fail("An empty-ledger error must never provision a voucher");
  }, async () => new Response(JSON.stringify({ status: "error", messages: "Data not found." })));
  await assert.rejects(emptyPayments.sync(), /Mutasi Qiospay belum tersedia/);
  assert.equal((await payments.status(invoice.reference_id))?.status, "pending");
  assert.equal(fulfillCalls.length, 0);
  const { rows } = await pool.query("SELECT config_key,config_value FROM settings WHERE config_key IN ('qiospaySyncError','qiospayLastSyncAt')");
  assert.match(rows.find(r => r.config_key === "qiospaySyncError")?.config_value || "", /Mutasi Qiospay belum tersedia/);
  assert.ok(!rows.some(r => r.config_key === "qiospayLastSyncAt" && r.config_value));
});
test("unconfigured/misconfigured/no-router checkout cannot take payment or mint voucher", async () => {
  config.qiospayApiKey = "";
  await assert.rejects(order(), /belum lengkap/);
  config = fixtureConfig();
  await assert.rejects(payments.create({ id: 1 }, 5000, 1, null), /router/);
  await assert.rejects(payments.create(pkg, 5000, null, "x"), /Nomor HP/);
  await assert.rejects(payments.create(pkg, 0, 1, null), /Harga/);
  assert.equal(fulfillCalls.length, 0);
});
test("creation renders QR locally, charges unique total, and reuses one active invoice", async () => {
  const a = await order();
  const b = await order();
  assert.equal(a.reference_id, b.reference_id);
  assert.equal(a.amount, 5000 + a.unique_code);
  assert.ok(a.unique_code >= 1 && a.unique_code <= 999);
  assert.match(a.qr_url, /^data:image\/png;base64,/);
  assert.equal(a.status, "pending");
  assert.equal(fulfillCalls.length, 0);
});
test("parallel buyers of the same package receive different totals", async () => {
  const results = await Promise.all([order("081234567891"), order("081234567892"), order("081234567893")]);
  assert.equal(new Set(results.map(r => r.amount)).size, 3);
  assert.equal(new Set(results.map(r => r.reference_id)).size, 3);
});
test("expired invoice total is never recycled, even for the same buyer", async () => {
  const a = await order();
  await pool.query("UPDATE qiospay_invoices SET expires_at=NOW()-INTERVAL '1 second' WHERE reference_id=$1", [a.reference_id]);
  assert.equal((await payments.status(a.reference_id))?.status, "expired");
  const b = await order();
  assert.notEqual(a.amount, b.amount);
});
test("already existing merchant credits cannot pay a new invoice", async () => {
  ledger = Array.from({ length: 998 }, (_, i) => credit(5001 + i, `old-${i}`, new Date(Date.now() - 86400_000)));
  const a = await order();
  assert.equal(a.amount, 5999);
  const data = await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "pending");
  assert.equal(data.reservations_count, 1);
  await assert.rejects(order("081234567899"), /habis/);
});
test("no ledger credit and wrong amounts never mint vouchers", async () => {
  const a = await order(); await inWindow(a.reference_id);
  await payments.sync();
  ledger = [credit(a.amount + 1), { ...credit(a.amount), type: "DB" }];
  await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "pending");
  assert.equal(fulfillCalls.length, 0);
});
test("verified ledger credit fulfills once across duplicate/concurrent syncs", async () => {
  const a = await order(); await inWindow(a.reference_id);
  ledger = [credit(a.amount)];
  await Promise.all([payments.sync(), payments.sync()]);
  await payments.sync();
  const status = await payments.status(a.reference_id);
  assert.equal(status?.status, "success");
  assert.equal(status?.voucher_code, fulfillCalls[0]);
  assert.equal(fulfillCalls.length, 1);
  assert.equal((await payments.overview()).events[0].status, "matched");
});
test("router outage keeps verified money and retries the SAME voucher candidate", async () => {
  const a = await order(); await inWindow(a.reference_id);
  ledger = [credit(a.amount)]; failRouter = true;
  await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "paid");
  assert.equal((await payments.status(a.reference_id))?.voucher_code, null);
  await payments.sync();
  assert.equal(fulfillCalls.length, 1, "backoff suppresses repeated provision");
  failRouter = false;
  await payments.provision(a.reference_id, true);
  assert.equal((await payments.status(a.reference_id))?.status, "success");
  assert.equal(fulfillCalls.length, 2);
  assert.equal(fulfillCalls[0], fulfillCalls[1]);
});
test("manual retry cannot mint a voucher before money is verified", async () => {
  const a = await order();
  await assert.rejects(payments.provision(a.reference_id, true), /Dana belum/);
  assert.equal(fulfillCalls.length, 0);
});
test("late payment is review-only and cannot mint a voucher", async () => {
  const a = await order();
  await pool.query("UPDATE qiospay_invoices SET created_at=NOW()-INTERVAL '20 minutes',expires_at=NOW()-INTERVAL '10 minutes' WHERE reference_id=$1", [a.reference_id]);
  ledger = [credit(a.amount)];
  await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "review");
  assert.equal((await payments.overview()).events[0].status, "review");
  assert.equal(fulfillCalls.length, 0);
});
test("delayed ledger delivery recovers an expired invoice paid INSIDE its window", async () => {
  const a = await order();
  await pool.query("UPDATE qiospay_invoices SET created_at=NOW()-INTERVAL '20 minutes',expires_at=NOW()-INTERVAL '10 minutes' WHERE reference_id=$1", [a.reference_id]);
  assert.equal((await payments.status(a.reference_id))?.status, "expired");
  ledger = [credit(a.amount, "delayed", new Date(Date.now() - 15 * 60_000))];
  await payments.sync();
  assert.equal((await payments.status(a.reference_id))?.status, "success");
  assert.equal(fulfillCalls.length, 1);
});
test("repeat actual payments do not create a second voucher; surplus is marked review", async () => {
  const a = await order(); await inWindow(a.reference_id);
  ledger = [credit(a.amount, "first"), credit(a.amount, "second")];
  await payments.sync();
  assert.equal(fulfillCalls.length, 1);
  const statuses = (await payments.overview()).events.map(e => e.status).sort();
  assert.deepEqual(statuses, ["matched", "review"]);
});
test("immutable ledger references reject changed amounts without minting", async () => {
  const a = await order(); await inWindow(a.reference_id);
  ledger = [credit(a.amount + 10, "immutable")];
  await payments.sync();
  ledger = [credit(a.amount, "immutable")];
  await assert.rejects(payments.sync(), /berubah/);
  assert.equal(fulfillCalls.length, 0);
});
test("nominal reservation blocks accidental removal of financial history", async () => {
  const a = await order();
  await assert.rejects(pool.query("DELETE FROM transactions WHERE reference_id=$1", [a.reference_id]), /foreign key/);
  assert.equal((await payments.status(a.reference_id))?.status, "pending");
});
test("browser receipt recovery is scoped, discards corrupt data, and never hydrates voucher fields", () => {
  const data = new Map<string, string>();
  (globalThis as any).window = { sessionStorage: {
    getItem: (k: string) => data.get(k) ?? null,
    setItem: (k: string, v: string) => data.set(k, v),
    removeItem: (k: string) => data.delete(k),
    key: (i: number) => [...data.keys()][i] ?? null,
    get length() { return data.size; },
  } };
  try {
    const a = qrisRecoveryKey("user-1", 1), b = qrisRecoveryKey("user-2", 1);
    const payment = { provider: "qiospay", reference_id: "TEST-REF", qr_url: "data:image/png;base64,AA==",
      amount: 5123, base_amount: 5000, unique_code: 123, expires_at: new Date(Date.now() + 60_000).toISOString() };
    storeQrisRecovery(a, { ...payment, voucher_code: "DO-NOT-HYDRATE" } as any);
    assert.equal(readQrisRecovery(a)?.reference_id, "TEST-REF");
    assert.equal((readQrisRecovery(a) as any).voucher_code, undefined);
    assert.equal(readQrisRecovery(b), null);
    storeQrisRecovery(b, payment);
    clearQrisRecoveryForIdentity("user-1");
    assert.equal(readQrisRecovery(a), null);
    assert.ok(readQrisRecovery(b));
    storeQrisRecovery(a, { ...payment, qr_url: "javascript:alert(1)" });
    assert.equal(readQrisRecovery(a), null);
    assert.equal(data.has(a), false);
    storeQrisRecovery(a, { ...payment, provider: "sanpay", unique_code: 0, amount: 5000,
      qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=test", expires_at: null } as any);
    assert.equal(readQrisRecovery(a), null, "Retired gateway receipts cannot reopen checkout");
    storeQrisRecovery(a, { ...payment, amount: 9999 });
    assert.equal(readQrisRecovery(a), null);
  } finally { delete (globalThis as any).window; }
});